import JsPic from '../../assets/img/images.png';

export const rowCourse = [
    {
      id:1,
      title: " Js",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "in Progress",
      time: 2,
      lastUpdate: "2023-1-2",
      rating: "4.5",
    },
    {
      id:2,
      title: " Py",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "not Started",
      time: 2,
      lastUpdate: "2022-3-1",
      rating: "4.5",
    },
    {
      id:3,
      title: " Ts",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "completed",
      time: 2,
      lastUpdate: "2023-4-3",
      rating: "4.5",
    },
    {
      id:4,
      title: " NodeJs",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "in Progress",
      time: 2,
      lastUpdate: "2022-3-7",
      rating: "4.5",
    },
    {
      id:5,
      title: " C++",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "completed",
      time: 2,
      lastUpdate: "2024-4-9",
      rating: "4.5",
    },
    {
      id:6,
      title: " C",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "not Started",
      time: 2,
      lastUpdate: "2024-4-5",
      rating: "4.5",
    },
    {
      id:7,
      title: " Java",
      pic: JsPic,
      teacher: "mahya Rastegari",
      student: 230,
      status: "not Started",
      time: 2,
      lastUpdate: "2024-5-2",
      rating: "4.5",
    },
  ]